### ISSUE TITLE
Request: Tag

### ISSUE THREAD

**Issue by Kutalmis-Bercin** [OFDataCommittee/openfoam-smartsim#25]
Hello @AndreWeiner 

Could you please add a tag for v2406 so that OpenFOAM submodules can have a non-moving target SHA?

Many thanks.

**Comment by AndreWeiner** [comment]
Hi Kuti,
we'll have a short internal discussion about wheater there is anything else we'd like to merge before creating the tag. Most likely that won't be the case.
Cheers
Andre

**Comment by Kutalmis-Bercin** [comment]
Thanks Andre,

It would be wonderful if this could happen within this week. My apologies for causing any inconveniences.

Kind regards, Kuti

**Comment by AndreWeiner** [comment]
Sure, no problem. We'll have a tag by the end of the day.
Best, Andre

**Comment by AndreWeiner** [comment]
Hi Kuti,
the tag is now available.
Best, Andre

**Comment by Kutalmis-Bercin** [comment]
Thank you very much Andre; highly appreciated.
Kind regards, Kuti
