### ISSUE TITLE
SmartRedis compilation error with current dev branch

### ISSUE THREAD

**Issue by AndreWeiner** [OFDataCommittee/openfoam-smartsim#30]
@tmaric @ashao @FoamScience @al-rigazzi some fun activities before Christmas:

There appears to be a compilation error when compiling against the current OpenFOAM-dev version. This error needs to be fixed before the next release (typically at the end of the year). Otherwise, the submodule will be deactivated. I'll check the error and update this issue.

Best, Andre

**Comment by al-rigazzi** [comment]
Interesting, I think I have compiled (on an HPE Cray EX) a few weeks ago and everything looked fine. I'll look into this as soon as possible.

**Comment by AndreWeiner** [comment]
@al-rigazzi did you compile against the develop branch? For v2412, they will switch from c++14 to c++17. Could that be an issue? I am still compiling the latest version of develop...

**Comment by al-rigazzi** [comment]
@AndreWeiner I thought I was on `develop`, but I'll do everything from scratch, I may also have a slightly older version of SmartRedis on that system. If you could paste here the error you get, I'll try to replicate it.

**Comment by AndreWeiner** [comment]
There is an issue when compiling the repository for the very first time, and `FOAM_USER_LIBBIN` does not exist. In that case, copying the SmartRedis binaries fails, and the linker has nothing to link against. I couldn't reproduce any other compilation errors.

**Comment by FoamScience** [comment]
Ok, maybe you can:
1. Add a check to Allwmake if OpenFOAM is sourced - something like:
```bash
if [ -z "$FOAM_ETC" ]; then
  echo "Please source an OpenFOAM version"
  exit 1
fi
```
2. Make sure FOAM_USER_LIBBIN exists on disk if the user hasn't created it yet:
```bash
mkdir -p $FOAM_USER_LIBBIN
mkdir -p $FOAM_USER_APPBIN
```

Also, it might be better to add `set -e` near the top of Allwmake so it errors out on first failing command.

**Comment by FoamScience** [comment]
BTW, if OpenFOAM devs don't like us creating these folders at this point, when compiling the plugin, they can always:
`FOAM_USER_LIBBIN=$FOAM_LIBBIN FOAM_USER_APPBIN=$FOAM_APPBIN ./Allwmake`

This will trick the repo into compiling to standard OpenFOAM libs/bins folders

**Comment by tmaric** [comment]
@FoamScience if we redirect to FOAM_LIBBIN and FOAM_APPIN, then the module compilation fails for regular user with OpenFOAM installed somewhere in / as a package?

**Comment by FoamScience** [comment]
> @FoamScience if we redirect to FOAM_LIBBIN and FOAM_APPIN, then the module compilation fails for regular user with OpenFOAM installed somewhere in / as a package?

I mean this depends on how OpenGOAM drvs want to do things. Will they compile plugins with the rest of the code base? For example when building binary packages? Or will they require users to compile the plugins they are interested in?

Either way, fo us, user folders are the way, we just have to make sure those folders exist (it appears out plugin gets compiled first?)

The thing is, they are compiling with wmake -all instead of Allwmake so not sure how to create those folders on our end!

**Comment by tmaric** [comment]
Sub-modules are not all compiled automatically, you need to as a user do `git submodule init && git submodule update && cd modules && ./Allwmake` to build them. I think for now just creating FOAM_USER_APPBIN will work fine, and it should cover also the scenario where the user installed OF in a folder outside of normal-user rights.

**Comment by AndreWeiner** [comment]
Final update: The compilation error was related to missing C++17 features in an older GCC version used on a testing machine. Nonetheless, the check for FOAM_USER_LIBBIN is sensible, so I merged Tomislav's commit. `wmake` checks for the user folders and creates them is necessary (FOAM_USER_APPBIN and FOAM_USER_LIBBIN). That's why, even on a fresh system, running `Allwmake` twice leads to a successful compilation the second time.
Cheers
